<?php

use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinces = array(
            array('name' => 'آذربايجان شرقي', 'element_id' => 11, 'is_default' => 0, 'creator_ip' => '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'آذربايجان غربي', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'اردبيل', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'اصفهان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'البرز', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'ايلام', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'بوشهر', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'تهران', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'چهارمحال بختياري', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'خراسان جنوبي', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'خراسان رضوي', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'خراسان شمالي', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'خوزستان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'زنجان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'سمنان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'سيستان و بلوچستان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'فارس', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'قزوين', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'قم', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'كردستان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'كرمان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'كرمانشاه', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'كهكيلويه و بويراحمد', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'گلستان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'گيلان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'لرستان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'مازندران', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'مركزي', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'هرمزگان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'همدان', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
            array('name' => 'يزد', 'element_id' => 11, 'is_default' => 0, 'creator_ip', '127.0.0.1', 'creator_id' => 99, 'created_at' => '2019-05-05 05:05:05'),
        );

        $cities = array(
            array('province_id' =>  25        ,'name' => 'تبريز'),
            array('province_id' =>  28        ,'name' => 'كندوان'),
            array('province_id' =>  28        ,'name' => 'بندر شرفخانه'),
            array('province_id' =>  28        ,'name' => 'مراغه'),
            array('province_id' =>  28        ,'name' => 'ميانه'),
            array('province_id' =>  28        ,'name' => 'شبستر'),
            array('province_id' =>  28        ,'name' => 'مرند'),
            array('province_id' =>  28        ,'name' => 'جلفا'),
            array('province_id' =>  28        ,'name' => 'سراب'),
            array('province_id' =>  28        ,'name' => 'هاديشهر'),
            array('province_id' =>  28        ,'name' => 'بناب'),
            array('province_id' =>  28        ,'name' => 'كليبر'),
            array('province_id' =>  28        ,'name' => 'تسوج'),
            array('province_id' =>  28        ,'name' => 'اهر'),
            array('province_id' =>  28        ,'name' => 'هريس'),
            array('province_id' =>  28        ,'name' => 'عجبشير'),
            array('province_id' =>  28        ,'name' => 'هشترود'),
            array('province_id' =>  28        ,'name' => 'ملكان'),
            array('province_id' =>  28        ,'name' => 'بستان آباد'),
            array('province_id' =>  28        ,'name' => 'ورزقان'),
            array('province_id' =>  28        ,'name' => 'اسكو'),
            array('province_id' =>  28        ,'name' => 'آذر شهر'),
            array('province_id' =>  28        ,'name' => 'قره آغاج'),
            array('province_id' =>  28        ,'name' => 'ممقان'),
            array('province_id' =>  28        ,'name' => 'صوفیان'),
            array('province_id' =>  28        ,'name' => 'ایلخچی'),
            array('province_id' =>  28        ,'name' => 'خسروشهر'),
            array('province_id' =>  28        ,'name' => 'باسمنج'),
            array('province_id' =>  28        ,'name' => 'سهند'),
            array('province_id' =>  28        ,'name' => 'اروميه'),
            array('province_id' =>  29        ,'name' => 'نقده'),
            array('province_id' =>  29        ,'name' => 'ماكو'),
            array('province_id' =>  29        ,'name' => 'تكاب'),
            array('province_id' =>  29        ,'name' => 'خوي'),
            array('province_id' =>  29        ,'name' => 'مهاباد'),
            array('province_id' =>  29        ,'name' => 'سر دشت'),
            array('province_id' =>  29        ,'name' => 'چالدران'),
            array('province_id' =>  29        ,'name' => 'بوكان'),
            array('province_id' =>  29        ,'name' => 'مياندوآب'),
            array('province_id' =>  29        ,'name' => 'سلماس'),
            array('province_id' =>  29        ,'name' => 'شاهين دژ'),
            array('province_id' =>  29        ,'name' => 'پيرانشهر'),
            array('province_id' =>  29        ,'name' => 'سيه چشمه'),
            array('province_id' =>  29        ,'name' => 'اشنويه'),
            array('province_id' =>  29        ,'name' => 'چایپاره'),
            array('province_id' =>  29        ,'name' => 'پلدشت'),
            array('province_id' =>  29        ,'name' => 'شوط'),
            array('province_id' =>  29        ,'name' => 'اردبيل'),
            array('province_id' =>  30        ,'name' => 'سرعين'),
            array('province_id' =>  30        ,'name' => 'بيله سوار'),
            array('province_id' =>  30        ,'name' => 'پارس آباد'),
            array('province_id' =>  30        ,'name' => 'خلخال'),
            array('province_id' =>  30        ,'name' => 'مشگين شهر'),
            array('province_id' =>  30        ,'name' => 'مغان'),
            array('province_id' =>  30        ,'name' => 'نمين'),
            array('province_id' =>  30        ,'name' => 'نير'),
            array('province_id' =>  30        ,'name' => 'كوثر'),
            array('province_id' =>  30        ,'name' => 'كيوي'),
            array('province_id' =>  30        ,'name' => 'گرمي'),
            array('province_id' =>  30        ,'name' => 'اصفهان'),
            array('province_id' =>  31        ,'name' => 'فريدن'),
            array('province_id' =>  31        ,'name' => 'فريدون شهر'),
            array('province_id' =>  31        ,'name' => 'فلاورجان'),
            array('province_id' =>  31        ,'name' => 'گلپايگان'),
            array('province_id' =>  31        ,'name' => 'دهاقان'),
            array('province_id' =>  31        ,'name' => 'نطنز'),
            array('province_id' =>  31        ,'name' => 'نايين'),
            array('province_id' =>  31        ,'name' => 'تيران'),
            array('province_id' =>  31        ,'name' => 'كاشان'),
            array('province_id' =>  31        ,'name' => 'فولاد شهر'),
            array('province_id' =>  31        ,'name' => 'اردستان'),
            array('province_id' =>  31        ,'name' => 'سميرم'),
            array('province_id' =>  31        ,'name' => 'درچه'),
            array('province_id' =>  31        ,'name' => 'کوهپایه'),
            array('province_id' =>  31        ,'name' => 'مباركه'),
            array('province_id' =>  31        ,'name' => 'شهرضا'),
            array('province_id' =>  31        ,'name' => 'خميني شهر'),
            array('province_id' =>  31        ,'name' => 'شاهين شهر'),
            array('province_id' =>  31        ,'name' => 'نجف آباد'),
            array('province_id' =>  31        ,'name' => 'دولت آباد'),
            array('province_id' =>  31        ,'name' => 'زرين شهر'),
            array('province_id' =>  31        ,'name' => 'آران و بيدگل'),
            array('province_id' =>  31        ,'name' => 'باغ بهادران'),
            array('province_id' =>  31        ,'name' => 'خوانسار'),
            array('province_id' =>  31        ,'name' => 'مهردشت'),
            array('province_id' =>  31        ,'name' => 'علويجه'),
            array('province_id' =>  31        ,'name' => 'عسگران'),
            array('province_id' =>  31        ,'name' => 'نهضت آباد'),
            array('province_id' =>  31        ,'name' => 'حاجي آباد'),
            array('province_id' =>  31        ,'name' => 'تودشک'),
            array('province_id' =>  31        ,'name' => 'ورزنه'),
            array('province_id' =>  31        ,'name' => 'ايلام'),
            array('province_id' =>  33        ,'name' => 'مهران'),
            array('province_id' =>  33        ,'name' => 'دهلران'),
            array('province_id' =>  33        ,'name' => 'آبدانان'),
            array('province_id' =>  33        ,'name' => 'شيروان چرداول'),
            array('province_id' =>  33        ,'name' => 'دره شهر'),
            array('province_id' =>  33        ,'name' => 'ايوان'),
            array('province_id' =>  33        ,'name' => 'سرابله'),
            array('province_id' =>  33        ,'name' => 'بوشهر'),
            array('province_id' =>  34        ,'name' => 'تنگستان'),
            array('province_id' =>  34        ,'name' => 'دشتستان'),
            array('province_id' =>  34        ,'name' => 'دير'),
            array('province_id' =>  34        ,'name' => 'ديلم'),
            array('province_id' =>  34        ,'name' => 'كنگان'),
            array('province_id' =>  34        ,'name' => 'گناوه'),
            array('province_id' =>  34        ,'name' => 'ريشهر'),
            array('province_id' =>  34        ,'name' => 'دشتي'),
            array('province_id' =>  34        ,'name' => 'خورموج'),
            array('province_id' =>  34        ,'name' => 'اهرم'),
            array('province_id' =>  34        ,'name' => 'برازجان'),
            array('province_id' =>  34        ,'name' => 'خارك'),
            array('province_id' =>  34        ,'name' => 'جم'),
            array('province_id' =>  34        ,'name' => 'کاکی'),
            array('province_id' =>  34        ,'name' => 'عسلویه'),
            array('province_id' =>  34        ,'name' => 'بردخون'),
            array('province_id' =>  34        ,'name' => 'تهران'),
            array('province_id' =>  35        ,'name' => 'ورامين'),
            array('province_id' =>  35        ,'name' => 'فيروزكوه'),
            array('province_id' =>  35        ,'name' => 'ري'),
            array('province_id' =>  35        ,'name' => 'دماوند'),
            array('province_id' =>  35        ,'name' => 'اسلامشهر'),
            array('province_id' =>  35        ,'name' => 'رودهن'),
            array('province_id' =>  35        ,'name' => 'لواسان'),
            array('province_id' =>  35        ,'name' => 'بومهن'),
            array('province_id' =>  35        ,'name' => 'تجريش'),
            array('province_id' =>  35        ,'name' => 'فشم'),
            array('province_id' =>  35        ,'name' => 'كهريزك'),
            array('province_id' =>  35        ,'name' => 'پاكدشت'),
            array('province_id' =>  35        ,'name' => 'چهاردانگه'),
            array('province_id' =>  35        ,'name' => 'شريف آباد'),
            array('province_id' =>  35        ,'name' => 'قرچك'),
            array('province_id' =>  35        ,'name' => 'باقرشهر'),
            array('province_id' =>  35        ,'name' => 'شهريار'),
            array('province_id' =>  35        ,'name' => 'رباط كريم'),
            array('province_id' =>  35        ,'name' => 'قدس'),
            array('province_id' =>  35        ,'name' => 'ملارد'),
            array('province_id' =>  35        ,'name' => 'شهركرد'),
            array('province_id' =>  36        ,'name' => 'فارسان'),
            array('province_id' =>  36        ,'name' => 'بروجن'),
            array('province_id' =>  36        ,'name' => 'چلگرد'),
            array('province_id' =>  36        ,'name' => 'اردل'),
            array('province_id' =>  36        ,'name' => 'لردگان'),
            array('province_id' =>  36        ,'name' => 'سامان'),
            array('province_id' =>  36         ,'name' => 'قائن'),
            array('province_id' =>  37         ,'name' => 'فردوس'),
            array('province_id' =>  37         ,'name' => 'بيرجند'),
            array('province_id' =>  37         ,'name' => 'نهبندان'),
            array('province_id' =>  37         ,'name' => 'سربيشه'),
            array('province_id' =>  37         ,'name' => 'طبس مسینا'),
            array('province_id' =>  37         ,'name' => 'قهستان'),
            array('province_id' =>  37         ,'name' => 'درمیان'),
            array('province_id' =>  37         ,'name' => 'مشهد'),
            array('province_id' =>  38         ,'name' => 'نيشابور'),
            array('province_id' =>  38         ,'name' => 'سبزوار'),
            array('province_id' =>  38         ,'name' => 'كاشمر'),
            array('province_id' =>  38         ,'name' => 'گناباد'),
            array('province_id' =>  38         ,'name' => 'طبس'),
            array('province_id' =>  38         ,'name' => 'تربت حيدريه'),
            array('province_id' =>  38         ,'name' => 'خواف'),
            array('province_id' =>  38         ,'name' => 'تربت جام'),
            array('province_id' =>  38         ,'name' => 'تايباد'),
            array('province_id' =>  38         ,'name' => 'قوچان'),
            array('province_id' =>  38         ,'name' => 'سرخس'),
            array('province_id' =>  38         ,'name' => 'بردسكن'),
            array('province_id' =>  38         ,'name' => 'فريمان'),
            array('province_id' =>  38         ,'name' => 'چناران'),
            array('province_id' =>  38         ,'name' => 'درگز'),
            array('province_id' =>  38         ,'name' => 'كلات'),
            array('province_id' =>  38         ,'name' => 'طرقبه'),
            array('province_id' =>  38         ,'name' => 'سر ولایت'),
            array('province_id' =>  38         ,'name' => 'بجنورد'),
            array('province_id' =>  39         ,'name' => 'اسفراين'),
            array('province_id' =>  39         ,'name' => 'جاجرم'),
            array('province_id' =>  39         ,'name' => 'شيروان'),
            array('province_id' =>  39         ,'name' => 'آشخانه'),
            array('province_id' =>  39         ,'name' => 'گرمه'),
            array('province_id' =>  39         ,'name' => 'ساروج'),
            array('province_id' =>  39         ,'name' => 'اهواز'),
            array('province_id' =>  40         ,'name' => 'ايرانشهر'),
            array('province_id' =>  40         ,'name' => 'شوش'),
            array('province_id' =>  40         ,'name' => 'آبادان'),
            array('province_id' =>  40         ,'name' => 'خرمشهر'),
            array('province_id' =>  40         ,'name' => 'مسجد سليمان'),
            array('province_id' =>  40         ,'name' => 'ايذه'),
            array('province_id' =>  40         ,'name' => 'شوشتر'),
            array('province_id' =>  40         ,'name' => 'انديمشك'),
            array('province_id' =>  40         ,'name' => 'سوسنگرد'),
            array('province_id' =>  40         ,'name' => 'هويزه'),
            array('province_id' =>  40         ,'name' => 'دزفول'),
            array('province_id' =>  40         ,'name' => 'شادگان'),
            array('province_id' =>  40         ,'name' => 'بندر ماهشهر'),
            array('province_id' =>  40         ,'name' => 'بندر امام خميني'),
            array('province_id' =>  40         ,'name' => 'اميديه'),
            array('province_id' =>  40         ,'name' => 'بهبهان'),
            array('province_id' =>  40         ,'name' => 'رامهرمز'),
            array('province_id' =>  40         ,'name' => 'باغ ملك'),
            array('province_id' =>  40         ,'name' => 'هنديجان'),
            array('province_id' =>  40         ,'name' => 'لالي'),
            array('province_id' =>  40         ,'name' => 'رامشیر'),
            array('province_id' =>  40         ,'name' => 'حمیدیه'),
            array('province_id' =>  40         ,'name' => 'دغاغله'),
            array('province_id' =>  40         ,'name' => 'ملاثانی'),
            array('province_id' =>  40         ,'name' => 'شادگان'),
            array('province_id' =>  40         ,'name' => 'ویسی'),
            array('province_id' =>  40         ,'name' => 'زنجان'),
            array('province_id' =>  41         ,'name' => 'ابهر'),
            array('province_id' =>  41         ,'name' => 'خدابنده'),
            array('province_id' =>  41         ,'name' => 'طارم'),
            array('province_id' =>  41         ,'name' => 'ماهنشان'),
            array('province_id' =>  41         ,'name' => 'خرمدره'),
            array('province_id' =>  41         ,'name' => 'ايجرود'),
            array('province_id' =>  41         ,'name' => 'زرين آباد'),
            array('province_id' =>  41         ,'name' => 'آب بر'),
            array('province_id' =>  41         ,'name' => 'قيدار'),
            array('province_id' =>  41         ,'name' => 'سمنان'),
            array('province_id' =>  42         ,'name' => 'شاهرود'),
            array('province_id' =>  42         ,'name' => 'گرمسار'),
            array('province_id' =>  42         ,'name' => 'ايوانكي'),
            array('province_id' =>  42         ,'name' => 'دامغان'),
            array('province_id' =>  42         ,'name' => 'بسطام'),
            array('province_id' =>  42         ,'name' => 'زاهدان'),
            array('province_id' =>  43         ,'name' => 'چابهار'),
            array('province_id' =>  43         ,'name' => 'خاش'),
            array('province_id' =>  43         ,'name' => 'سراوان'),
            array('province_id' =>  43         ,'name' => 'زابل'),
            array('province_id' =>  43         ,'name' => 'سرباز'),
            array('province_id' =>  43         ,'name' => 'نيكشهر'),
            array('province_id' =>  43         ,'name' => 'ايرانشهر'),
            array('province_id' =>  43         ,'name' => 'راسك'),
            array('province_id' =>  43         ,'name' => 'ميرجاوه'),
            array('province_id' =>  43         ,'name' => 'شيراز'),
            array('province_id' =>  44         ,'name' => 'اقليد'),
            array('province_id' =>  44         ,'name' => 'داراب'),
            array('province_id' =>  44         ,'name' => 'فسا'),
            array('province_id' =>  44         ,'name' => 'مرودشت'),
            array('province_id' =>  44         ,'name' => 'خرم بيد'),
            array('province_id' =>  44         ,'name' => 'آباده'),
            array('province_id' =>  44         ,'name' => 'كازرون'),
            array('province_id' =>  44         ,'name' => 'ممسني'),
            array('province_id' =>  44         ,'name' => 'سپيدان'),
            array('province_id' =>  44         ,'name' => 'لار'),
            array('province_id' =>  44         ,'name' => 'فيروز آباد'),
            array('province_id' =>  44         ,'name' => 'جهرم'),
            array('province_id' =>  44         ,'name' => 'ني ريز'),
            array('province_id' =>  44         ,'name' => 'استهبان'),
            array('province_id' =>  44         ,'name' => 'لامرد'),
            array('province_id' =>  44         ,'name' => 'مهر'),
            array('province_id' =>  44         ,'name' => 'حاجي آباد'),
            array('province_id' =>  44         ,'name' => 'نورآباد'),
            array('province_id' =>  44         ,'name' => 'اردكان'),
            array('province_id' =>  44         ,'name' => 'صفاشهر'),
            array('province_id' =>  44         ,'name' => 'ارسنجان'),
            array('province_id' =>  44         ,'name' => 'قيروكارزين'),
            array('province_id' =>  44         ,'name' => 'سوريان'),
            array('province_id' =>  44         ,'name' => 'فراشبند'),
            array('province_id' =>  44         ,'name' => 'سروستان'),
            array('province_id' =>  44         ,'name' => 'ارژن'),
            array('province_id' =>  44         ,'name' => 'گويم'),
            array('province_id' =>  44         ,'name' => 'داريون'),
            array('province_id' =>  44         ,'name' => 'زرقان'),
            array('province_id' =>  44         ,'name' => 'خان زنیان'),
            array('province_id' =>  44         ,'name' => 'کوار'),
            array('province_id' =>  44         ,'name' => 'ده بید'),
            array('province_id' =>  44         ,'name' => 'باب انار/خفر'),
            array('province_id' =>  44         ,'name' => 'بوانات'),
            array('province_id' =>  44         ,'name' => 'خرامه'),
            array('province_id' =>  44         ,'name' => 'خنج'),
            array('province_id' =>  44         ,'name' => 'سیاخ دارنگون'),
            array('province_id' =>  44         ,'name' => 'قزوين'),
            array('province_id' =>  45         ,'name' => 'تاكستان'),
            array('province_id' =>  45         ,'name' => 'آبيك'),
            array('province_id' =>  45         ,'name' => 'بوئين زهرا'),
            array('province_id' =>  45         ,'name' => 'قم'),
            array('province_id' =>  46        ,'name' => 'طالقان'),
            array('province_id' =>  32        ,'name' => 'نظرآباد'),
            array('province_id' =>  32        ,'name' => 'اشتهارد'),
            array('province_id' =>  32        ,'name' => 'هشتگرد'),
            array('province_id' =>  32        ,'name' => 'كن'),
            array('province_id' =>  32        ,'name' => 'آسارا'),
            array('province_id' =>  32        ,'name' => 'شهرک گلستان'),
            array('province_id' =>  32        ,'name' => 'اندیشه'),
            array('province_id' =>  32        ,'name' => 'كرج'),
            array('province_id' =>  32        ,'name' => 'نظر آباد'),
            array('province_id' =>  32        ,'name' => 'گوهردشت'),
            array('province_id' =>  32        ,'name' => 'ماهدشت'),
            array('province_id' =>  32        ,'name' => 'مشکین دشت'),
            array('province_id' =>  32         ,'name' => 'سنندج'),
            array('province_id' =>  47         ,'name' => 'ديواندره'),
            array('province_id' =>  47         ,'name' => 'بانه'),
            array('province_id' =>  47         ,'name' => 'بيجار'),
            array('province_id' =>  47         ,'name' => 'سقز'),
            array('province_id' =>  47         ,'name' => 'كامياران'),
            array('province_id' =>  47         ,'name' => 'قروه'),
            array('province_id' =>  47         ,'name' => 'مريوان'),
            array('province_id' =>  47         ,'name' => 'صلوات آباد'),
            array('province_id' =>  47         ,'name' => 'حسن آباد'),
            array('province_id' =>  47         ,'name' => 'كرمان'),
            array('province_id' =>  48         ,'name' => 'راور'),
            array('province_id' =>  48         ,'name' => 'بابك'),
            array('province_id' =>  48         ,'name' => 'انار'),
            array('province_id' =>  48         ,'name' => 'کوهبنان'),
            array('province_id' =>  48         ,'name' => 'رفسنجان'),
            array('province_id' =>  48         ,'name' => 'بافت'),
            array('province_id' =>  48         ,'name' => 'سيرجان'),
            array('province_id' =>  48         ,'name' => 'كهنوج'),
            array('province_id' =>  48         ,'name' => 'زرند'),
            array('province_id' =>  48         ,'name' => 'بم'),
            array('province_id' =>  48         ,'name' => 'جيرفت'),
            array('province_id' =>  48         ,'name' => 'بردسير'),
            array('province_id' =>  48         ,'name' => 'كرمانشاه'),
            array('province_id' =>  49         ,'name' => 'اسلام آباد غرب'),
            array('province_id' =>  49         ,'name' => 'سر پل ذهاب'),
            array('province_id' =>  49         ,'name' => 'كنگاور'),
            array('province_id' =>  49         ,'name' => 'سنقر'),
            array('province_id' =>  49         ,'name' => 'قصر شيرين'),
            array('province_id' =>  49         ,'name' => 'گيلان غرب'),
            array('province_id' =>  49         ,'name' => 'هرسين'),
            array('province_id' =>  49         ,'name' => 'صحنه'),
            array('province_id' =>  49         ,'name' => 'پاوه'),
            array('province_id' =>  49         ,'name' => 'جوانرود'),
            array('province_id' =>  49         ,'name' => 'شاهو'),
            array('province_id' =>  49         ,'name' => 'ياسوج'),
            array('province_id' =>  50         ,'name' => 'گچساران'),
            array('province_id' =>  50         ,'name' => 'دنا'),
            array('province_id' =>  50         ,'name' => 'دوگنبدان'),
            array('province_id' =>  50         ,'name' => 'سي سخت'),
            array('province_id' =>  50         ,'name' => 'دهدشت'),
            array('province_id' =>  50         ,'name' => 'ليكك'),
            array('province_id' =>  50         ,'name' => 'گرگان'),
            array('province_id' =>  51         ,'name' => 'آق قلا'),
            array('province_id' =>  51         ,'name' => 'گنبد كاووس'),
            array('province_id' =>  51         ,'name' => 'علي آباد كتول'),
            array('province_id' =>  51         ,'name' => 'مينو دشت'),
            array('province_id' =>  51         ,'name' => 'تركمن'),
            array('province_id' =>  51         ,'name' => 'كردكوي'),
            array('province_id' =>  51         ,'name' => 'بندر گز'),
            array('province_id' =>  51         ,'name' => 'كلاله'),
            array('province_id' =>  51         ,'name' => 'آزاد شهر'),
            array('province_id' =>  51         ,'name' => 'راميان'),
            array('province_id' =>  51         ,'name' => 'رشت'),
            array('province_id' =>  52         ,'name' => 'منجيل'),
            array('province_id' =>  52         ,'name' => 'لنگرود'),
            array('province_id' =>  52         ,'name' => 'رود سر'),
            array('province_id' =>  52         ,'name' => 'تالش'),
            array('province_id' =>  52         ,'name' => 'آستارا'),
            array('province_id' =>  52         ,'name' => 'ماسوله'),
            array('province_id' =>  52         ,'name' => 'آستانه اشرفيه'),
            array('province_id' =>  52         ,'name' => 'رودبار'),
            array('province_id' =>  52         ,'name' => 'فومن'),
            array('province_id' =>  52         ,'name' => 'صومعه سرا'),
            array('province_id' =>  52         ,'name' => 'بندرانزلي'),
            array('province_id' =>  52         ,'name' => 'كلاچاي'),
            array('province_id' =>  52         ,'name' => 'هشتپر'),
            array('province_id' =>  52         ,'name' => 'رضوان شهر'),
            array('province_id' =>  52         ,'name' => 'ماسال'),
            array('province_id' =>  52         ,'name' => 'شفت'),
            array('province_id' =>  52         ,'name' => 'سياهكل'),
            array('province_id' =>  52         ,'name' => 'املش'),
            array('province_id' =>  52         ,'name' => 'لاهیجان'),
            array('province_id' =>  52         ,'name' => 'خشک بيجار'),
            array('province_id' =>  52         ,'name' => 'خمام'),
            array('province_id' =>  52         ,'name' => 'لشت نشا'),
            array('province_id' =>  52         ,'name' => 'بندر کياشهر'),
            array('province_id' =>  52         ,'name' => 'خرم آباد'),
            array('province_id' =>  53         ,'name' => 'ماهشهر'),
            array('province_id' =>  53         ,'name' => 'دزفول'),
            array('province_id' =>  53         ,'name' => 'بروجرد'),
            array('province_id' =>  53         ,'name' => 'دورود'),
            array('province_id' =>  53         ,'name' => 'اليگودرز'),
            array('province_id' =>  53         ,'name' => 'ازنا'),
            array('province_id' =>  53         ,'name' => 'نور آباد'),
            array('province_id' =>  53         ,'name' => 'كوهدشت'),
            array('province_id' =>  53         ,'name' => 'الشتر'),
            array('province_id' =>  53         ,'name' => 'پلدختر'),
            array('province_id' =>  53         ,'name' => 'ساري'),
            array('province_id' =>  54         ,'name' => 'آمل'),
            array('province_id' =>  54         ,'name' => 'بابل'),
            array('province_id' =>  54         ,'name' => 'بابلسر'),
            array('province_id' =>  54         ,'name' => 'بهشهر'),
            array('province_id' =>  54         ,'name' => 'تنكابن'),
            array('province_id' =>  54         ,'name' => 'جويبار'),
            array('province_id' =>  54         ,'name' => 'چالوس'),
            array('province_id' =>  54         ,'name' => 'رامسر'),
            array('province_id' =>  54         ,'name' => 'سواد كوه'),
            array('province_id' =>  54         ,'name' => 'قائم شهر'),
            array('province_id' =>  54         ,'name' => 'نكا'),
            array('province_id' =>  54         ,'name' => 'نور'),
            array('province_id' =>  54         ,'name' => 'بلده'),
            array('province_id' =>  54         ,'name' => 'نوشهر'),
            array('province_id' =>  54         ,'name' => 'پل سفيد'),
            array('province_id' =>  54         ,'name' => 'محمود آباد'),
            array('province_id' =>  54         ,'name' => 'فريدون كنار'),
            array('province_id' =>  54         ,'name' => 'اراك'),
            array('province_id' =>  55         ,'name' => 'آشتيان'),
            array('province_id' =>  55         ,'name' => 'تفرش'),
            array('province_id' =>  55         ,'name' => 'خمين'),
            array('province_id' =>  55         ,'name' => 'دليجان'),
            array('province_id' =>  55         ,'name' => 'ساوه'),
            array('province_id' =>  55         ,'name' => 'سربند'),
            array('province_id' =>  55         ,'name' => 'محلات'),
            array('province_id' =>  55         ,'name' => 'شازند'),
            array('province_id' =>  55         ,'name' => 'بندرعباس'),
            array('province_id' =>  56         ,'name' => 'قشم'),
            array('province_id' =>  56         ,'name' => 'كيش'),
            array('province_id' =>  56         ,'name' => 'بندر لنگه'),
            array('province_id' =>  56         ,'name' => 'بستك'),
            array('province_id' =>  56         ,'name' => 'حاجي آباد'),
            array('province_id' =>  56         ,'name' => 'دهبارز'),
            array('province_id' =>  56         ,'name' => 'انگهران'),
            array('province_id' =>  56         ,'name' => 'ميناب'),
            array('province_id' =>  56         ,'name' => 'ابوموسي'),
            array('province_id' =>  56         ,'name' => 'بندر جاسك'),
            array('province_id' =>  56         ,'name' => 'تنب بزرگ'),
            array('province_id' =>  56         ,'name' => 'بندر خمیر'),
            array('province_id' =>  56         ,'name' => 'پارسیان'),
            array('province_id' =>  56         ,'name' => 'قشم'),
            array('province_id' =>  56         ,'name' => 'همدان'),
            array('province_id' =>  57         ,'name' => 'ملاير'),
            array('province_id' =>  57         ,'name' => 'تويسركان'),
            array('province_id' =>  57         ,'name' => 'نهاوند'),
            array('province_id' =>  57         ,'name' => 'كبودر اهنگ'),
            array('province_id' =>  57         ,'name' => 'رزن'),
            array('province_id' =>  57         ,'name' => 'اسدآباد'),
            array('province_id' =>  57         ,'name' => 'بهار'),
            array('province_id' =>  57         ,'name' => 'يزد'),
            array('province_id' =>  58         ,'name' => 'تفت'),
            array('province_id' =>  58         ,'name' => 'اردكان'),
            array('province_id' =>  58         ,'name' => 'ابركوه'),
            array('province_id' =>  58         ,'name' => 'ميبد'),
            array('province_id' =>  58         ,'name' => 'طبس'),
            array('province_id' =>  58         ,'name' => 'بافق'),
            array('province_id' =>  58         ,'name' => 'مهريز'),
            array('province_id' =>  58         ,'name' => 'اشكذر'),
            array('province_id' =>  58         ,'name' => 'هرات'),
            array('province_id' =>  58         ,'name' => 'خضرآباد'),
            array('province_id' =>  58         ,'name' => 'شاهديه'),
            array('province_id' =>  58         ,'name' => 'حمیدیه شهر'),
            array('province_id' =>  58         ,'name' => 'سید میرزا'),
            array('province_id' =>  58         ,'name' => 'زارچ')
        );

//        foreach($provinces as $province){
//                \App\Province::insert($provinces);
//        }

//        foreach($cities as $city){
//            \App\City::insert($cities);
//        }

    }
}
