<?php

use Illuminate\Database\Seeder;

class ElementTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $elements = [
            [
                'id'                => 1,
                'name'              => 'first_name',
                'label'             => 'نام',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'validation_rule'   =>'/^[ آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]+$/',
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,


            ],
            [
                'id'                => 2,
                'name'              => 'last_name',
                'label'             => 'نام خانوادگی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'validation_rule'   =>'/^[ آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]+$/',
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,

            ],
            [
                'id'                => 3,
                'name'              => 'father_name',
                'label'             => 'نام پدر',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'validation_rule'   =>'/^[ آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]+$/',
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,

            ],
            [
                'id'                => 4,
                'name'              => 'gender_id',
                'label'             => 'جنسیت',
                'element_type_id'   => 6,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 5,
                'name'              => 'id_certificate',
                'label'             => 'شماره شناسنامه',
                'element_type_id'   => 8,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 6,
                'name'              => 'series_letter_certificate ',
                'label'             => 'حرف سری شناسنامه',
                'element_type_id'   => 9,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 7,
                'name'              => 'series_number_certificate',
                'label'             => 'سری عددی شناسنامه',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 8,
                'name'              => 'serial_certificate',
                'label'             => 'سریال شناسنامه',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 9,
                'name'              => 'national_code',
                'label'             => 'کد ملی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 10,
                'name'              => 'birth_date',
                'label'             => 'تاریخ تولد',
                'element_type_id'   => 10,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 11,
                'name'              => 'religion_id',
                'label'             => 'دین',
                'element_type_id'   => 6,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 12,
                'name'              => 'religion_text',
                'label'             => 'عنوان دین',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>false,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 13,
                'name'              => 'nationality_id',
                'label'             => 'تابعیت',
                'element_type_id'   => 5,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 14,
                'name'              => 'phone',
                'label'             => 'شماره تلفن ثابت',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 15,
                'name'              => 'prefix_phone',
                'label'             => 'شماره تلفن شهرستان',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],

            [
                'id'                => 16,
                'name'              => 'mobile',
                'label'             => 'شماره تلفن همراه',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],

            [
                'id'                => 17,
                'name'              => 'email',
                'label'             => 'پست الکترونیکی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],

            [
                'id'                => 18,
                'name'              => 'province_id',
                'label'             => 'استان محل سکونت',
                'element_type_id'   => 11,
                'parent_id'         => 13,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],

            [
                'id'                => 19,
                'name'              => 'birth_province_id',
                'label'             => 'استان محل تولد',
                'element_type_id'   => 11,
                'parent_id'         => 13,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 20,
                'name'              => 'zip_code',
                'label'             => 'کدپستی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 21,
                'name'              => 'address',
                'label'             => 'آدرس محل سکونت',
                'element_type_id'   => 2,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 22,
                'name'              => 'military_status_id',
                'label'             => 'وضعیت نظام وظیفه',
                'element_type_id'   => 9,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 23,
                'name'              => 'physical_condition_id',
                'label'             => 'وضعیت جسمانی',
                'element_type_id'   => 5,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 24,
                'name'              => 'quota_id',
                'label'             => 'استفاده از سهمیه پذیرش',
                'element_type_id'   => 6,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 25,
                'name'              => 'duration_in_war_month',
                'label'             => 'مدت حضور در جبهه',
                'element_type_id'   => 8,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 26,
                'name'              => 'duration_in_war_day',
                'label'             => 'مدت حضور در جبهه',
                'element_type_id'   => 8,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 27,
                'name'              => 'tracking_code',
                'label'             => 'کد پیگیری ۱۲ رقمی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 28,
                'name'              => 'graduated',
                'label'             => 'دانش‌آموز یا فارغ‌التحصیل',
                'element_type_id'   => 6,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],[
                'id'                => 29,
                'name'              => 'diploma_id',
                'label'             => 'عنوان دیپلم',
                'element_type_id'   => 9,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],[
                'id'                => 30,
                'name'              => 'diploma_province_id',
                'label'             => 'استان اخذ دیپلم',
                'element_type_id'   => 11,
                'parent_id'         => 13,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 31,
                'name'              => 'academic_status',
                'label'             => 'وضعیت تحصیلی در آموزش عالی',
                'element_type_id'   => 6,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 32,
                'name'              => 'student_code',
                'label'             => 'کد دانش‌آموزی',
                'element_type_id'   => 8,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 33,
                'name'              => 'diploma_date',
                'label'             => 'تاریخ اخذ مدرک دیپلم',
                'element_type_id'   => 10,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 34,
                'name'              => 'pre_university_grade',
                'label'             => 'معدل کل دوره پیش‌دانشگاهی',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 35,
                'name'              => 'written_diploma_grade',
                'label'             => 'معدل کتبی دیپلم',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 36,
                'name'              => 'total_diploma_grade',
                'label'             => 'معدل کل دیپلم',
                'element_type_id'   => 1,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 37,
                'name'              => 'associate_grade',
                'label'             => 'معدل کل دوره کاردانی',
                'element_type_id'   => 1,
                'required'          =>true,
                'parent_id'         => null,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 38,
                'name'              => 'associate_province_id',
                'label'             => 'استان محل اخذ فوق دیپلم',
                'element_type_id'   => 9,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 39,
                'name'              => 'associate_date',
                'label'             => 'تاریخ اخذ مدرک فوق دیپلم',
                'element_type_id'   => 10,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 40,
                'name'              => 'user_image',
                'label'             => 'عکس داوطلب',
                'element_type_id'   => 7,
                'parent_id'         => null,
                'required'          =>true,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
            [
                'id'                => 44,
                'name'              => 'foreigners_code',
                'label'             => 'کد اتباع خارجی',
                'element_type_id'   => 8,
                'parent_id'         => null,
                'required'          =>false,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'placeholder'       =>null,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
                'validation_rule'   =>null,
            ],
        ];

        \App\Element::insert($elements);
    }
}
