<?php

use Illuminate\Database\Seeder;

class ElementValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $alphabeta = ['ا', 'ب', 'پ', 'ت', 'ث', 'ج', 'چ', 'ح', 'خ', 'د',
            'ذ', 'ر', 'ز', 'ژ', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع',
            'غ', 'ف', 'ق', 'ک', 'گ', 'ل', 'م', 'ن', 'و', 'ه', 'ی'];

        $i = 0;

        for ($alphabet = 0; $alphabet <= 31; $alphabet++) {

            $alphabet_value[] = [
                'id' => 61 + $alphabet,
                'name' => $alphabeta[$i++],
                'element_id' => 6,
                'is_default' => ($alphabet == 0) ? true : false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ];
        }


        \App\ElementValue::insert($alphabet_value);


        $element_value = [
            [
                'id' => 1,
                'name' => 'اسلام',
                'element_id' => 11,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'مسیحی',
                'element_id' => 11,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'کلیمی',
                'element_id' => 11,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => 4,
                'name' => 'زرتشتی',
                'element_id' => 11,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'سایر',
                'element_id' => 11,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'دانشجوی انصرافی',
                'element_id' => 31,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'دانشجوی دوره روزانه',
                'element_id' => 31,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'دانشجوی دوره غیر روزانه',
                'element_id' => 31,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فارغ‌التحصیل مقطع کاردانی',
                'element_id' => 31,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فارغ‌التحصیل مقطع کارشناسی',
                'element_id' => 31,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فارغ‌التحصیل مقطع کارشناسی ارشد و بالاتر',
                'element_id' => 31,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
/////////////


            [
                'id' => null,
                'name' => 'آزاد',
                'element_id' => 24,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'خانواده شهدا (پدر،مادر،خواهر و برادر شهید)',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'جانباز ۲۵ درصد و بالاتر',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند جانباز ۲۵ درصد و بالاتر',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'همسر جانباز ۲۵ درصد و بالاتر',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'آزادگان',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند آزاده',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [

                'id' => null,
                'name' => 'همسر آزاده',
                'element_id' => 24,
                'is_default' => false,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'دوره پیش‌دانشگاهی',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند شهید و مفقودالاثر',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'همسر شهید و مفقودالاثر',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'رزمنده داوطلب بسیجی (اعزام از سپاه)',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'رزمنده وزارت جهاد کشاورزی',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'رزمنده ستاد کل نیروهای مسلح',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'جانباز کمتر از ۲۵ درصد',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند جانباز کمتر از ۲۵ درصد',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'همسر جانباز کمتر از ۲۵ درصد',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند رزمنده داوطلب بسیجی (اعزامی از سپاه)',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند رزمنده وزارت جهاد کشاورزی',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'فرزند رزمنده ستاد کل نیروهای مسلح',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'همسر رزمنده داوطلب بسیجی (اعزامی از سپاه)',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'همسر رزمنده وزارت جهاد کشاورزی',
                'element_id' => 24,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ]
            //////////////////
            ,
            [
                'id' => null,
                'name' => '1',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '2',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '3',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '4',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '5',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '6',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '7',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '8',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '9',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '10',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '11',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '12',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => '13',
                'element_id' => 22,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ]

            /////////////////
            , [
                'id' => null,
                'name' => 'دیپلم نظام قدیم',
                'element_id' => 28,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'نظام جدید ۶-۳-۳',
                'element_id' => 28,
                'is_default' => false,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'ریاضی فیزیک',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'علوم تجربی',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'ادبیات و علوم انسانی',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'فنی و حرفه‌ای / کار و دانش',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'هنری',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'بهیاری',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'ماشین‌آلات کشاورزی',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'مدیریت روستایی / صنایع غذایی',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'علوم و معارف اسلامی',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'سایر دیپلم‌ها',
                'element_id' => 29,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'کم شنوا',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'نا شنوا',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'کم بینا',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'نا بینا',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => null,
                'name' => 'سالم',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ], [
                'id' => null,
                'name' => 'معلولیت جسمی و حرکتی',
                'element_id' => 23,
                'is_default' => true,
                'created_at' => \Carbon\Carbon::now()->toDateString(),
                'creator_ip' => '127.0.0.1',
                'creator_id' => \App\Admin::SEEDER_ID,
                'deleter_ip' => null,
                'updater_ip' => null,
                'updater_id' => null,
                'deleter_id' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

        ];

        \App\ElementValue::insert($element_value);

        $date = \Carbon\Carbon::now()->toDateString();
        \Illuminate\Support\Facades\DB::query("INSERT INTO `element_values` (`id`, `name`, `element_id`, `is_default`, `parent_id`, `creator_ip`, `deleter_ip`, `updater_ip`, `creator_id`, `updater_id`, `deleter_id`, `created_at`, `updated_at`, `deleted_at`) VALUES
(28, 'آذربايجان شرقي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(29, 'آذربايجان غربي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(30, 'اردبيل', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(31, 'اصفهان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(32, 'البرز', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(33, 'ايلام', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(34, 'بوشهر', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(35, 'تهران', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(36, 'چهارمحال بختياري', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(37, 'خراسان جنوبي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(38, 'خراسان رضوي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(39, 'خراسان شمالي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(40, 'خوزستان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(41, 'زنجان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(42, 'سمنان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(43, 'سيستان و بلوچستان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(44, 'فارس', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(45, 'قزوين', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(46, 'قم', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(47, 'كردستان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(48, 'كرمان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(49, 'كرمانشاه', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(50, 'كهكيلويه و بويراحمد', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(51, 'گلستان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(52, 'گيلان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(53, 'لرستان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(54, 'مازندران', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(55, 'مركزي', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(56, 'هرمزگان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(57, 'همدان', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL),
(58, 'يزد', 11, 0, NULL, '127.0.0.1', NULL, NULL, 99, NULL, NULL, '$date', NULL, NULL);");


    }
}
