<?php

use Illuminate\Database\Seeder;

class FormElementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $form_elements = [
            [
                'id'                => 1,
                'form_id'           => 1,
                'element_id'        => 1,
                'position'          =>1,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 2,
                'form_id'           => 1,
                'element_id'        => 2,
                'position'          =>2,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 3,
                'form_id'           => 1,
                'element_id'        => 3,
                'position'          =>3,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 4,
                'form_id'           => 1,
                'element_id'        => 4,
                'position'          =>4,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 5,
                'form_id'           => 1,
                'element_id'        => 5,
                'position'          =>5,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 6,
                'form_id'           => 1,
                'element_id'        => 6,
                'position'          =>6,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 7,
                'form_id'           => 1,
                'element_id'        => 7,
                'position'          =>7,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 8,
                'form_id'           => 1,
                'element_id'        => 8,
                'position'          =>8,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 9,
                'form_id'           => 1,
                'element_id'        => 9,
                'position'          =>9,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 10,
                'form_id'           => 1,
                'element_id'        => 10,
                'position'          =>10,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 11,
                'form_id'           => 1,
                'element_id'        => 11,
                'position'          =>11,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 12,
                'form_id'           => 1,
                'element_id'        => 12,
                'position'          =>12,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 13,
                'form_id'           => 1,
                'element_id'        => 13,
                'position'          =>13,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 14,
                'form_id'           => 1,
                'element_id'        => 14,
                'position'          =>14,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 15,
                'form_id'           => 1,
                'element_id'        => 15,
                'position'          =>15,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 16,
                'form_id'           => 1,
                'element_id'        => 16,
                'position'          =>16,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],[
                'id'                => 17,
                'form_id'           => 1,
                'element_id'        => 17,
                'position'          =>17,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 18,
                'form_id'           => 1,
                'element_id'        => 18,
                'position'          =>18,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 19,
                'form_id'           => 1,
                'element_id'        => 19,
                'position'          =>19,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 20,
                'form_id'           => 1,
                'element_id'        => 20,
                'position'          =>20,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],[
                'id'                => 21,
                'form_id'           => 1,
                'element_id'        => 21,
                'position'          =>21,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 22,
                'form_id'           => 1,
                'element_id'        => 22,
                'position'          =>22,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 23,
                'form_id'           => 1,
                'element_id'        => 23,
                'position'          =>23,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 24,
                'form_id'           => 1,
                'element_id'        => 24,
                'position'          =>24,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 25,
                'form_id'           => 1,
                'element_id'        => 25,
                'position'          =>25,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 26,
                'form_id'           => 1,
                'element_id'        => 26,
                'position'          =>26,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 27,
                'form_id'           => 1,
                'element_id'        => 27,
                'position'          =>27,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],[
                'id'                => 28,
                'form_id'           => 1,
                'element_id'        => 28,
                'position'          =>28,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],[
                'id'                => 29,
                'form_id'           => 1,
                'element_id'        => 29,
                'position'          =>29,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 30,
                'form_id'           => 1,
                'element_id'        => 30,
                'position'          =>30,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 31,
                'form_id'           => 1,
                'element_id'        => 31,
                'position'          =>31,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 32,
                'form_id'           => 1,
                'element_id'        => 32,
                'position'          =>32,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 33,
                'form_id'           => 1,
                'element_id'        => 33,
                'position'          =>33,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 34,
                'form_id'           => 1,
                'element_id'        => 34,
                'position'          =>34,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 35,
                'form_id'           => 1,
                'element_id'        => 35,
                'position'          =>35,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 36,
                'form_id'           => 1,
                'element_id'        => 36,
                'position'          =>36,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 37,
                'form_id'           => 1,
                'element_id'        => 37,
                'position'          =>37,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 38,
                'form_id'           => 1,
                'element_id'        => 38,
                'position'          =>38,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 39,
                'form_id'           => 1,
                'element_id'        => 39,
                'position'          =>39,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],
            [
                'id'                => 40,
                'form_id'           => 1,
                'element_id'        => 40,
                'position'          => 40,
                'created_at'        =>\Carbon\Carbon::now()->toDateString(),
                'creator_ip'        =>'127.0.0.1',
                'creator_id'        =>\App\Admin::SEEDER_ID,
                'deleter_ip'        =>null,
                'updater_ip'        =>null,
                'updater_id'        =>null,
                'deleter_id'        =>null,
                'updated_at'        =>null,
                'deleted_at'        =>null,
            ],

        ];

        \App\FormElement::insert($form_elements);
    }
}
